version: "3"
services:
  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
    container_name: "flaskapp"
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    container_name: "redis"
